import { useEffect, useMemo, useRef, useState } from 'react';
import AdminLayout from '../components/AdminLayout';
import PageContainer from '../components/PageContainer';
import PanelCard from '../components/PanelCard';
import DataTable from '../components/DataTable';
import CalendarView from '../components/CalendarView';
import RichEditor from '../components/RichEditor';
import { apiRequest, formatDateTime, localizeField } from '../lib/api';
import { useAdminI18n } from '../lib/i18n';

function slugify(text) {
  return text
    .toString()
    .toLowerCase()
    .trim()
    .replace(/['']/g, '')
    .replace(/[^а-яa-z0-9\s-]/g, '')
    .replace(/[\s_]+/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '');
}

const EMPTY_LOCALIZED = { ua: '', ru: '', en: '' };

const DEFAULT_FORM = {
  title: { ...EMPTY_LOCALIZED },
  slug: '',
  shortDescription: { ...EMPTY_LOCALIZED },
  fullDescription: { ...EMPTY_LOCALIZED },
  posterImage: '',
  startAt: '',
  endAt: '',
  status: 'DRAFT',
  isFeatured: false,
  ctaType: 'BOOKING',
  ticketUrl: ''
};



function normalizeLocalized(value) {
  if (!value || typeof value !== 'object') {
    return { ...EMPTY_LOCALIZED, ua: value || '' };
  }

  return {
    ua: value.ua || value.uk || value.ru || value.en || '',
    ru: value.ru || '',
    en: value.en || ''
  };
}

function toDateTimeLocal(value) {
  if (!value) return '';
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return '';
  const kyivStr = date.toLocaleString('sv-SE', { timeZone: 'Europe/Kyiv' });
  return kyivStr.slice(0, 16);
}

function fromDateTimeLocal(value) {
  if (!value) return null;
  const parts = String(value).split('T');
  if (parts.length !== 2) return null;
  const [datePart, timePart] = parts;
  const [year, month, day] = datePart.split('-').map(Number);
  const [hour, minute] = timePart.split(':').map(Number);
  const wallClockUtc = Date.UTC(year, month - 1, day, hour, minute);
  const getKyivOffset = (date) => {
    const values = Object.fromEntries(new Intl.DateTimeFormat('en-CA', {
      timeZone: 'Europe/Kyiv',
      year: 'numeric', month: '2-digit', day: '2-digit',
      hour: '2-digit', minute: '2-digit', second: '2-digit', hourCycle: 'h23'
    }).formatToParts(date).map((part) => [part.type, part.value]));
    return Date.UTC(
      Number(values.year), Number(values.month) - 1, Number(values.day),
      Number(values.hour), Number(values.minute), Number(values.second)
    ) - Math.floor(date.getTime() / 1000) * 1000;
  };
  let utcDate = new Date(wallClockUtc - getKyivOffset(new Date(wallClockUtc)));
  utcDate = new Date(wallClockUtc - getKyivOffset(utcDate));
  return Number.isNaN(utcDate.getTime()) ? null : utcDate.toISOString();
}

function getLocaleCode(locale) {
  return locale.toUpperCase();
}

export default function EventsPage() {
  const { t, language } = useAdminI18n();
  const [viewMode, setViewMode] = useState('table');
  const [state, setState] = useState({ loading: true, error: '', events: [] });
  const [form, setForm] = useState(DEFAULT_FORM);
  const [editId, setEditId] = useState(null);
  const [savingKey, setSavingKey] = useState('');
  const [isSlugLocked, setIsSlugLocked] = useState(true);
  const [activeLocale, setActiveLocale] = useState('ua');
  const [showPosterUrl, setShowPosterUrl] = useState(false);
  const [posterUploadState, setPosterUploadState] = useState({ status: 'idle', details: '' });
  const [translating, setTranslating] = useState({});
  const [feedback, setFeedback] = useState({ tone: '', message: '' });
  const isFormDirty = useRef(false);
  const slugAutoGenerated = useRef(false);

  const [sessions, setSessions] = useState([]);
  const [sessionForm, setSessionForm] = useState({ name: { ua: '', ru: '', en: '' }, startsAt: '', endsAt: '', isActive: true, admissionMode: 'TICKETED' });
  const [editingSessionId, setEditingSessionId] = useState(null);
  const [sessionsSaving, setSessionsSaving] = useState(false);
  const [ticketTypes, setTicketTypes] = useState([]);
  const [typeForm, setTypeForm] = useState({ name: { ua: '', ru: '', en: '' }, price: '', capacity: '', eventSessionId: '' });
  const [editingTypeId, setEditingTypeId] = useState(null);
  const [typesSaving, setTypesSaving] = useState(false);

  const stats = useMemo(() => {
    const total = state.events.length;
    const published = state.events.filter((event) => event.status === 'PUBLISHED').length;
    const featured = state.events.filter((event) => event.isFeatured).length;
    return { total, published, featured };
  }, [state.events]);

  const publicPreviewHref = useMemo(() => {
    if (!editId || !form.slug) return '';
    return `/events/${form.slug}`;
  }, [editId, form.slug]);

  async function loadEvents() {
    setState((current) => ({ ...current, loading: true, error: '' }));

    const { response, body } = await apiRequest('/api/admin/events');
    if (!response.ok) {
      setState({ loading: false, error: body.message || t('eventsAdmin.errors.load'), events: [] });
      return;
    }

    setState({ loading: false, error: '', events: Array.isArray(body) ? body : [] });
  }

  async function loadEventWithDetails(id) {
    const { response, body } = await apiRequest(`/api/admin/events/${id}`);
    if (!response.ok) return;
    setSessions(Array.isArray(body.sessions) ? body.sessions : []);
    setTicketTypes(Array.isArray(body.ticketTypes) ? body.ticketTypes : []);
  }

  useEffect(() => {
    loadEvents().catch(() => {
      setState({ loading: false, error: t('eventsAdmin.errors.load'), events: [] });
    });
  }, [language]);

  function resetForm() {
    if (isFormDirty.current && !window.confirm(t('eventsAdmin.form.discardConfirm'))) return;
    setForm({
      ...DEFAULT_FORM,
      title: { ...EMPTY_LOCALIZED },
      shortDescription: { ...EMPTY_LOCALIZED },
      fullDescription: { ...EMPTY_LOCALIZED }
    });
    setEditId(null);
    setActiveLocale('ua');
    setShowPosterUrl(false);
    setIsSlugLocked(true);
    slugAutoGenerated.current = false;
    isFormDirty.current = false;
    setPosterUploadState({ status: 'idle', details: '' });
    setSessions([]);
    setSessionForm({ name: { ua: '', ru: '', en: '' }, startsAt: '', endsAt: '', isActive: true, admissionMode: 'TICKETED' });
    setEditingSessionId(null);
    setSessionsSaving(false);
    setTicketTypes([]);
    setTypeForm({ name: { ua: '', ru: '', en: '' }, price: '', capacity: '', eventSessionId: '' });
    setEditingTypeId(null);
    setTypesSaving(false);
  }

  async function startEdit(event) {
    if (isFormDirty.current && !window.confirm(t('eventsAdmin.form.discardConfirm'))) return;
    let eventDetails = event;
    setFeedback({ tone: '', message: '' });
    const { response, body } = await apiRequest(`/api/admin/events/${event.id}`);
    if (response.ok && body) {
      eventDetails = body;
    } else {
      setFeedback({ tone: 'error', message: body.message || t('eventsAdmin.errors.load') });
    }

    setEditId(eventDetails.id);
    setForm({
      title: normalizeLocalized(eventDetails.title),
      slug: eventDetails.slug || '',
      shortDescription: normalizeLocalized(eventDetails.shortDescription),
      fullDescription: normalizeLocalized(eventDetails.fullDescription),
      posterImage: eventDetails.posterImage || '',
      startAt: toDateTimeLocal(eventDetails.startAt),
      endAt: toDateTimeLocal(eventDetails.endAt),
      status: eventDetails.status || 'DRAFT',
      isFeatured: Boolean(eventDetails.isFeatured),
      ctaType: eventDetails.ctaType || 'BOOKING',
      ticketUrl: eventDetails.ticketUrl || ''
    });
    setIsSlugLocked(true);
    slugAutoGenerated.current = true;
    isFormDirty.current = false;
    setActiveLocale('ua');
    setPosterUploadState({ status: 'idle', details: '' });
    setSessions(Array.isArray(eventDetails.sessions) ? eventDetails.sessions : []);
    setSessionForm({ name: { ua: '', ru: '', en: '' }, startsAt: '', endsAt: '', isActive: true, admissionMode: 'TICKETED' });
    setEditingSessionId(null);
    setSessionsSaving(false);
    setTicketTypes(Array.isArray(eventDetails.ticketTypes) ? eventDetails.ticketTypes : []);
    setTypeForm({ name: { ua: '', ru: '', en: '' }, price: '', capacity: '', eventSessionId: '' });
    setEditingTypeId(null);
    setTypesSaving(false);
    window.requestAnimationFrame(() => {
      window.scrollTo({ top: document.body.scrollHeight, behavior: 'smooth' });
    });
  }

  useEffect(() => {
    if (!editId && !slugAutoGenerated.current && form.title?.ua?.trim() && isSlugLocked) {
      const generated = slugify(form.title.ua);
      if (generated) {
        setForm((current) => ({ ...current, slug: generated }));
        slugAutoGenerated.current = true;
      }
    }
  }, [form.title?.ua, editId, isSlugLocked]);

  function markDirty() { isFormDirty.current = true; }

  function setLocalizedField(field, locale, value) {
    markDirty();
    setForm((current) => ({
      ...current,
      [field]: {
        ...current[field],
        [locale]: value
      }
    }));
  }

  async function autoTranslateField(field) {
    const sourceText = form[field]?.ua;
    if (!sourceText?.trim()) {
      setFeedback({ tone: 'error', message: t('eventsAdmin.form.placeholders.fillUaFirst') });
      return;
    }

    setTranslating((current) => ({ ...current, [field]: true }));
    const { response, body } = await apiRequest('/api/admin/translate', {
      method: 'POST',
      body: JSON.stringify({ text: sourceText, targetLangs: ['ru', 'en'] })
    });
    setTranslating((current) => ({ ...current, [field]: false }));

    if (!response.ok) {
      setFeedback({ tone: 'error', message: body.error || body.message || t('eventsAdmin.errors.translation') });
      return;
    }

    setForm((current) => ({
      ...current,
      [field]: {
        ...current[field],
        ru: body.ru || current[field].ru || '',
        en: body.en || current[field].en || ''
      }
    }));
    setFeedback({ tone: 'success', message: t('eventsAdmin.translationUpdated') });
  }

  function handleEditSession(idxOrId) {
    const session = editId ? sessions.find((s) => s.id === idxOrId) : sessions[idxOrId];
    if (!session) return;
    setSessionForm({
      name: session.name || { ua: '', ru: '', en: '' },
      startsAt: toDateTimeLocal(session.startsAt),
      endsAt: toDateTimeLocal(session.endsAt),
      isActive: session.isActive ?? true,
      admissionMode: session.admissionMode || 'TICKETED'
    });
    setEditingSessionId(idxOrId);
  }

  function handleDeleteSession(idxOrId) {
    if (!window.confirm(t('eventsAdmin.errors.confirmDeleteSession'))) return;
    if (editId) {
      const session = sessions.find((s) => s.id === idxOrId);
      if (session) deleteSession(session.id);
    } else {
      setSessions((prev) => prev.filter((_, i) => i !== idxOrId));
    }
  }

  function handleSaveSession(event) {
    event.preventDefault();
    if (!sessionForm.startsAt || !sessionForm.endsAt) {
      alert(language === 'ua' ? 'Будь ласка, вкажіть дату початку та закінчення сесії!' : language === 'ru' ? 'Пожалуйста, укажите дату начала и окончания сессии!' : 'Please specify session start and end dates!');
      return;
    }
    if (editId) {
      return saveSession(event);
    }
    const payload = {
      name: sessionForm.name,
      startsAt: fromDateTimeLocal(sessionForm.startsAt),
      endsAt: fromDateTimeLocal(sessionForm.endsAt),
      isActive: sessionForm.isActive,
      admissionMode: sessionForm.admissionMode
    };
    if (editingSessionId !== null) {
      setSessions((prev) => prev.map((s, i) => i === editingSessionId ? payload : s));
      setEditingSessionId(null);
    } else {
      setSessions((prev) => [...prev, payload]);
    }
    setSessionForm({ name: { ua: '', ru: '', en: '' }, startsAt: '', endsAt: '', isActive: true, admissionMode: 'TICKETED' });
  }

  function handleEditTicketType(id) {
    const tt = ticketTypes.find((t) => t.id === id);
    if (!tt) return;
    setTypeForm({
      name: tt.name || { ua: '', ru: '', en: '' },
      price: String(tt.price ?? ''),
      capacity: String(tt.capacity ?? ''),
      eventSessionId: String(tt.eventSessionId ?? '')
    });
    setEditingTypeId(id);
  }

  async function autoGenerateSessions() {
    if (!form.startAt) {
      alert(language === 'ua' ? 'Спочатку вкажіть дату початку заходу!' : language === 'ru' ? 'Сначала укажите дату начала мероприятия!' : 'Please specify the event start date first!');
      return;
    }

    if (sessions.length > 0) {
      const confirmMsg = language === 'ua' 
        ? 'Це замінить усі поточні сесії на нові автозгенеровані. Продовжити?'
        : language === 'ru'
        ? 'Это заменит все текущие сессии на новые автосгенерированные. Продолжить?'
        : 'This will replace all current sessions with newly auto-generated ones. Proceed?';
      if (!window.confirm(confirmMsg)) return;
    }

    const startDate = new Date(form.startAt);
    let endDate = form.endAt ? new Date(form.endAt) : null;
    if (!endDate) {
      endDate = new Date(startDate.getTime() + 4 * 60 * 60 * 1000); // 4 hours duration fallback
    }

    if (endDate < startDate) {
      alert(language === 'ua' ? 'Дата закінчення не може бути раніше дати початку!' : language === 'ru' ? 'Дата окончания не может быть раньше даты начала!' : 'End date cannot be earlier than start date!');
      return;
    }

    const generated = [];
    const diffTime = Math.abs(endDate - startDate);
    const diffDays = Math.ceil(diffTime / (1000 * 60 * 60 * 24));

    // If it's a single day event
    if (diffDays <= 1 && startDate.toDateString() === endDate.toDateString()) {
      generated.push({
        name: {
          ua: language === 'ua' ? 'Основний сеанс' : language === 'ru' ? 'Основной сеанс' : 'Main Session',
          ru: 'Основной сеанс',
          en: 'Main Session'
        },
        startsAt: toDateTimeLocal(startDate),
        endsAt: toDateTimeLocal(endDate),
        isActive: true,
        admissionMode: 'TICKETED'
      });
    } else {
      // Multi-day event: generate a daily session for each day in range
      let current = new Date(startDate);
      let dayIndex = 1;
      while (current <= endDate) {
        const sStart = new Date(current);
        const sEnd = new Date(current);
        
        sStart.setHours(startDate.getHours(), startDate.getMinutes(), 0, 0);
        sEnd.setHours(endDate.getHours(), endDate.getMinutes(), 0, 0);
        
        generated.push({
          name: {
            ua: `День ${dayIndex}`,
            ru: `День ${dayIndex}`,
            en: `Day ${dayIndex}`
          },
          startsAt: toDateTimeLocal(sStart),
          endsAt: toDateTimeLocal(sEnd),
          isActive: true,
          admissionMode: 'TICKETED'
        });

        current.setDate(current.getDate() + 1);
        dayIndex++;
      }
    }

    if (editId) {
      setSessionsSaving(true);
      setFeedback({ tone: '', message: '' });
      try {
        // Delete all existing sessions sequentially
        for (const s of sessions) {
          if (s.id) {
            await apiRequest(`/api/admin/event-sessions/${s.id}`, { method: 'DELETE' });
          }
        }
        
        // Create the newly generated sessions sequentially
        for (const s of generated) {
          const payload = {
            name: s.name,
            startsAt: fromDateTimeLocal(s.startsAt),
            endsAt: fromDateTimeLocal(s.endsAt),
            isActive: s.isActive
          };
          await apiRequest(`/api/admin/events/${editId}/sessions`, {
            method: 'POST',
            body: JSON.stringify(payload)
          });
        }
        await loadEventWithDetails(editId);
        setFeedback({ tone: 'success', message: language === 'ua' ? 'Сесії успішно автозгенеровані!' : language === 'ru' ? 'Сессии успешно автосгенерированы!' : 'Sessions successfully auto-generated!' });
      } catch (err) {
        setFeedback({ tone: 'error', message: language === 'ua' ? 'Помилка при автогенерації сесій.' : language === 'ru' ? 'Ошибка при автогенерации сессий.' : 'Failed to auto-generate sessions.' });
      } finally {
        setSessionsSaving(false);
      }
    } else {
      const formatted = generated.map(g => ({
        name: g.name,
        startsAt: fromDateTimeLocal(g.startsAt),
        endsAt: fromDateTimeLocal(g.endsAt),
        isActive: g.isActive
      }));
      setSessions(formatted);
      markDirty();
    }
  }

  async function submitForm(event) {
    event.preventDefault();
    setSavingKey('event-form');
    setFeedback({ tone: '', message: '' });

    const payload = {
      ...form,
      startAt: fromDateTimeLocal(form.startAt),
      endAt: form.endAt ? fromDateTimeLocal(form.endAt) : null,
      ...(!editId && sessions.length > 0 ? { sessions: sessions.map((s) => ({
        startsAt: s.startsAt,
        endsAt: s.endsAt,
        name: s.name || undefined,
        sortOrder: s.sortOrder || 0,
        isActive: s.isActive ?? true,
        admissionMode: s.admissionMode || 'TICKETED'
      })) } : {})
    };

    const path = editId ? `/api/admin/events/${editId}` : '/api/admin/events';
    const method = editId ? 'PATCH' : 'POST';
    const { response, body } = await apiRequest(path, {
      method,
      body: JSON.stringify(payload)
    });

    if (!response.ok) {
      setSavingKey('');
      setFeedback({ tone: 'error', message: body.message || t('eventsAdmin.errors.save') });
      return;
    }

    await loadEvents();
    const wasEditing = Boolean(editId);
    if (!wasEditing && body.event) {
      setEditId(body.event.id);
      if (body.event.sessions) setSessions(body.event.sessions);
      if (body.event.ticketTypes) setTicketTypes(body.event.ticketTypes);
    } else {
      resetForm();
    }
    setSavingKey('');
    setFeedback({ tone: 'success', message: wasEditing ? t('eventsAdmin.form.updated') : t('eventsAdmin.form.created') });
  }

  async function removeEvent(eventRow) {
    if (!window.confirm(t('eventsAdmin.form.deleteConfirm', { title: localizeField(eventRow.title, language) }))) return;

    setSavingKey(`delete-${eventRow.id}`);
    const { response, body } = await apiRequest(`/api/admin/events/${eventRow.id}`, { method: 'DELETE' });
    if (!response.ok) {
      setSavingKey('');
      setFeedback({ tone: 'error', message: response.status === 409 ? t('eventsAdmin.form.deleteBlocked') : (body.message || t('eventsAdmin.errors.delete')) });
      return;
    }

    await loadEvents();
    if (editId === eventRow.id) resetForm();
    setSavingKey('');
    setFeedback({ tone: 'success', message: t('eventsAdmin.form.deleted') });
  }

  async function autoTranslateAll() {
    const fields = ['title', 'shortDescription', 'fullDescription'];
    for (const field of fields) {
      const sourceText = form[field]?.ua;
      if (!sourceText?.trim()) continue;
      setTranslating((current) => ({ ...current, [field]: true }));
      const { response, body } = await apiRequest('/api/admin/translate', {
        method: 'POST',
        body: JSON.stringify({ text: sourceText, targetLangs: ['ru', 'en'] })
      });
      setTranslating((current) => ({ ...current, [field]: false }));
      if (response.ok) {
        setForm((current) => ({
          ...current,
          [field]: {
            ...current[field],
            ru: body.ru || current[field].ru || '',
            en: body.en || current[field].en || ''
          }
        }));
      }
    }
    setFeedback({ tone: 'success', message: t('eventsAdmin.translationUpdated') });
  }

  async function handlePosterUpload(file) {
    if (!file) return;
    setPosterUploadState({ status: 'uploading', details: file.name });
    const payload = new FormData();
    payload.append('folder', 'events');
    payload.append('image', file);
    const { response, body } = await apiRequest('/api/admin/uploads/image', { method: 'POST', body: payload });
    if (!response.ok || !body.url) {
      setPosterUploadState({ status: 'error', details: body.message || t('eventsAdmin.errors.upload') });
      setFeedback({ tone: 'error', message: body.message || t('eventsAdmin.errors.upload') });
      return;
    }
    setForm((current) => ({ ...current, posterImage: body.url }));
    setPosterUploadState({ status: 'success', details: body.url });
    setFeedback({ tone: 'success', message: t('eventsAdmin.posterUploaded') });
  }

  async function saveSession(event) {
    event.preventDefault();
    if (!editId) return;
    setSessionsSaving(true);
    const payload = {
      ...sessionForm,
      startsAt: fromDateTimeLocal(sessionForm.startsAt),
      endsAt: fromDateTimeLocal(sessionForm.endsAt)
    };
    const { response, body } = editingSessionId
      ? await apiRequest(`/api/admin/event-sessions/${editingSessionId}`, { method: 'PATCH', body: JSON.stringify(payload) })
      : await apiRequest(`/api/admin/events/${editId}/sessions`, { method: 'POST', body: JSON.stringify(payload) });
    setSessionsSaving(false);
    if (!response.ok) { setFeedback({ tone: 'error', message: body.message || t('eventsAdmin.errors.saveSession') }); return; }
    await loadEventWithDetails(editId);
    setSessionForm({ name: { ua: '', ru: '', en: '' }, startsAt: '', endsAt: '', isActive: true, admissionMode: 'TICKETED' });
    setEditingSessionId(null);
    setFeedback({ tone: 'success', message: editingSessionId ? t('eventsAdmin.form.sessionSaved') : t('eventsAdmin.form.sessionAdded') });
  }

  async function deleteSession(id) {
    if (!window.confirm(t('eventsAdmin.errors.confirmDeleteSession'))) return;
    setSessionsSaving(true);
    const { response, body } = await apiRequest(`/api/admin/event-sessions/${id}`, { method: 'DELETE' });
    setSessionsSaving(false);
    if (!response.ok) { setFeedback({ tone: 'error', message: body.message || t('eventsAdmin.errors.deleteSession') }); return; }
    await loadEventWithDetails(editId);
    setFeedback({ tone: 'success', message: t('eventsAdmin.form.sessionDeleted') });
  }

  async function saveTicketType(event) {
    event.preventDefault();
    if (!typeForm.name.ua || !typeForm.price) {
      alert(language === 'ua' ? 'Будь ласка, вкажіть назву та ціну квитка!' : language === 'ru' ? 'Пожалуйста, укажите название и цену билета!' : 'Please specify ticket name and price!');
      return;
    }
    if (!editId) return;
    setTypesSaving(true);
    const payload = {
      ...typeForm,
      eventSessionId: typeForm.eventSessionId ? Number(typeForm.eventSessionId) : null,
      price: Number(typeForm.price),
      capacity: Number(typeForm.capacity)
    };
    const { response, body } = editingTypeId
      ? await apiRequest(`/api/admin/ticket-types/${editingTypeId}`, { method: 'PATCH', body: JSON.stringify(payload) })
      : await apiRequest(`/api/admin/events/${editId}/ticket-types`, { method: 'POST', body: JSON.stringify(payload) });
    setTypesSaving(false);
    if (!response.ok) { setFeedback({ tone: 'error', message: body.message || t('eventsAdmin.errors.saveTariff') }); return; }
    await loadEventWithDetails(editId);
    setTypeForm({ name: { ua: '', ru: '', en: '' }, price: '', capacity: '', eventSessionId: '' });
    setEditingTypeId(null);
    setFeedback({ tone: 'success', message: editingTypeId ? t('eventsAdmin.form.tariffSaved') : t('eventsAdmin.form.tariffCreated') });
  }

  async function deleteTicketType(id) {
    if (!window.confirm(t('eventsAdmin.errors.confirmDeleteTariff'))) return;
    setTypesSaving(true);
    const { response, body } = await apiRequest(`/api/admin/ticket-types/${id}`, { method: 'DELETE' });
    setTypesSaving(false);
    if (!response.ok) { setFeedback({ tone: 'error', message: body.message || t('eventsAdmin.errors.deleteTariff') }); return; }
    await loadEventWithDetails(editId);
    setFeedback({ tone: 'success', message: t('eventsAdmin.form.tariffDeleted') });
  }

  async function toggleTicketType(id, isActive) {
    setTypesSaving(true);
    const { response, body } = await apiRequest(`/api/admin/ticket-types/${id}`, { method: 'PATCH', body: JSON.stringify({ isActive }) });
    setTypesSaving(false);
    if (!response.ok) { setFeedback({ tone: 'error', message: body.message || t('eventsAdmin.errors.updateTariff') }); return; }
    await loadEventWithDetails(editId);
    setFeedback({ tone: 'success', message: t('eventsAdmin.form.tariffUpdated') });
  }

  const columns = [
    { key: 'title', label: t('eventsAdmin.columns.title'), render: (row) => <strong>{localizeField(row.title, language)}</strong> },
    { key: 'startAt', label: t('eventsAdmin.columns.start'), render: (row) => formatDateTime(row.startAt, language === 'ua' ? 'uk-UA' : (language === 'ru' ? 'ru-RU' : 'en-US')) },
    { key: 'status', label: t('eventsAdmin.columns.status'), render: (row) => t(`eventsAdmin.statusOptions.${row.status}`) },
    { key: 'tickets', label: t('eventsAdmin.columns.tickets'), render: (row) => {
      const sessionsCount = row._sessionsCount ?? 0;
      const tariffsCount = row._ticketTypesCount ?? 0;
      return <span style={{ fontSize: 12, whiteSpace: 'nowrap' }}>{t('eventsAdmin.columns.ticketsInfo', { sessions: sessionsCount, tariffs: tariffsCount })}</span>;
    } },
    {
      key: 'actions',
      label: t('eventsAdmin.columns.actions'),
      render: (row) => (
        <div className="actions compact">
          <button type="button" className="btn btn-small btn-secondary" onClick={() => startEdit(row)}>{t('common.edit')}</button>
          <button type="button" className="btn btn-small btn-danger" disabled={savingKey === `delete-${row.id}`} onClick={() => removeEvent(row)}>{t('eventsAdmin.form.delete')}</button>
        </div>
      )
    }
  ];

  return (
    <AdminLayout>
      <PageContainer title={t('eventsAdmin.title')} description={t('eventsAdmin.description')}>
        <div className="metric-compact-grid">
          <div className="metric-compact-item">
            <strong>{stats.total}</strong>
            <span className="muted">{t('eventsAdmin.total')}</span>
          </div>
          <div className="metric-compact-item">
            <strong>{stats.published}</strong>
            <span className="muted">{t('eventsAdmin.published')}</span>
          </div>
          <div className="metric-compact-item">
            <strong>{stats.featured}</strong>
            <span className="muted">{t('eventsAdmin.featured')}</span>
          </div>
        </div>
        <div className="menu-admin-section-switch" role="tablist" style={{ marginTop: 14 }}>
          <button
            type="button"
            className={`menu-admin-section-switch-btn ${viewMode === 'table' ? 'active' : ''}`}
            onClick={() => setViewMode('table')}
          >
            {t('eventsAdmin.table')}
          </button>
          <button
            type="button"
            className={`menu-admin-section-switch-btn ${viewMode === 'calendar' ? 'active' : ''}`}
            onClick={() => setViewMode('calendar')}
          >
            {t('eventsAdmin.calendar')}
          </button>
        </div>

        {state.loading ? <p>{t('eventsAdmin.loading')}</p> : null}
        {state.error ? <p className="error">{state.error}</p> : null}
        {!state.loading && viewMode === 'table' ? (
          <DataTable columns={columns} rows={state.events} emptyText={t('eventsAdmin.empty')} />
        ) : null}
        {!state.loading && viewMode === 'calendar' ? (
          <CalendarView
            items={state.events.map((event) => ({
              id: event.id,
              event,
              date: event.startAt,
              title: localizeField(event.title, language),
              color: event.status === 'PUBLISHED' ? 'success' : event.status === 'DRAFT' ? 'neutral' : 'danger',
              renderItem: () => (
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', width: '100%', gap: 8 }}>
                  <div>
                    <strong>{localizeField(event.title, language)}</strong>
                    <div className="muted" style={{ fontSize: 11 }}>
                      {formatDateTime(event.startAt, language === 'ua' ? 'uk-UA' : (language === 'ru' ? 'ru-RU' : 'en-US'))}
                    </div>
                  </div>
                  <span className={`status-pill ${event.status === 'PUBLISHED' ? 'success' : event.status === 'DRAFT' ? 'neutral' : 'danger'}`}>
                    {t(`eventsAdmin.statusOptions.${event.status}`)}
                  </span>
                  <button
                    type="button"
                    className="btn btn-small btn-secondary"
                    onClick={(clickEvent) => {
                      clickEvent.stopPropagation();
                      startEdit(event);
                    }}
                  >
                    {t('common.edit')}
                  </button>
                </div>
              )
            }))}
            onItemClick={(item) => {
              if (item?.event) startEdit(item.event);
            }}
            onDateClick={(date) => {
              const match = state.events.find((event) => {
                const eventDate = new Date(event.startAt);
                return eventDate.getFullYear() === date.getFullYear()
                  && eventDate.getMonth() === date.getMonth()
                  && eventDate.getDate() === date.getDate();
              });
              if (match) {
                startEdit(match);
              }
            }}
          />
        ) : null}
      </PageContainer>

      <div className="grid-two-col" style={{ alignItems: 'start' }}>
        <PanelCard title={editId ? t('eventsAdmin.form.edit') : t('eventsAdmin.form.create')} subtitle="">
          <form onSubmit={submitForm} className="event-admin-form">
            <div className="grid-two-col">
              <label>
                {t('eventsAdmin.form.fields.title')} ({getLocaleCode('ua')}) <span className="required">*</span>
                <input value={form.title.ua} onChange={(event) => setLocalizedField('title', 'ua', event.target.value)} required />
              </label>
              <label>{t('eventsAdmin.form.fields.title')} ({getLocaleCode('ru')}) <input value={form.title.ru} onChange={(event) => setLocalizedField('title', 'ru', event.target.value)} placeholder={t('eventsAdmin.form.placeholders.autoTranslated')} /></label>
              <label>{t('eventsAdmin.form.fields.title')} ({getLocaleCode('en')}) <input value={form.title.en} onChange={(event) => setLocalizedField('title', 'en', event.target.value)} placeholder={t('eventsAdmin.form.placeholders.autoTranslated')} /></label>
              <label>
                {t('eventsAdmin.form.fields.slug')}
                <div style={{ display: 'flex', gap: 4 }}>
                  <input value={form.slug} onChange={(e) => { setForm({ ...form, slug: e.target.value }); markDirty(); }} disabled={isSlugLocked} style={{ flex: 1 }} />
                  <button type="button" className="btn btn-small btn-secondary" onClick={() => setIsSlugLocked(!isSlugLocked)} title={isSlugLocked ? t('common.unlock') : t('common.lock')}>
                    {isSlugLocked ? '🔒' : '🔓'}
                  </button>
                </div>
              </label>
            </div>

            <div className="grid-two-col" style={{ marginTop: '1rem' }}>
              <label>{t('eventsAdmin.form.fields.start')} <span className="required">*</span> <input type="datetime-local" value={form.startAt} onChange={(event) => { setForm({ ...form, startAt: event.target.value }); markDirty(); }} required /></label>
              <label>{t('eventsAdmin.form.fields.end')} <input type="datetime-local" value={form.endAt} onChange={(event) => { setForm({ ...form, endAt: event.target.value }); markDirty(); }} /></label>
              <label>
                {t('eventsAdmin.form.fields.status')}
                <select value={form.status} onChange={(event) => { setForm({ ...form, status: event.target.value }); markDirty(); }}>
                  <option value="DRAFT">{t('eventsAdmin.statusOptions.DRAFT')}</option>
                  <option value="PUBLISHED">{t('eventsAdmin.statusOptions.PUBLISHED')}</option>
                  <option value="ARCHIVED">{t('eventsAdmin.statusOptions.ARCHIVED')}</option>
                </select>
              </label>
              <label>
                {t('eventsAdmin.form.fields.cta')}
                <select value={form.ctaType} onChange={(event) => { setForm({ ...form, ctaType: event.target.value }); markDirty(); }}>
                  <option value="BOOKING">{t('eventsAdmin.ctaOptions.BOOKING')}</option>
                  <option value="TICKETS">{t('eventsAdmin.ctaOptions.TICKETS')}</option>
                  <option value="BOTH">{t('eventsAdmin.ctaOptions.BOTH')}</option>
                </select>
              </label>
            </div>

            <div className="admin-section-divider" style={{ marginTop: '1.5rem' }}>
              <hr /><span>{t('eventsAdmin.sectionSessions')}</span>
            </div>

            <div className="info-tip-box" style={{ background: 'rgba(201, 168, 108, 0.08)', border: '1px solid rgba(201, 168, 108, 0.25)', borderRadius: 6, padding: '10px 14px', marginBottom: 14, fontSize: 13, color: 'var(--text-muted)' }}>
              <strong>💡 {language === 'ua' ? 'Чому тут два блоки дат?' : language === 'ru' ? 'Почему здесь два блока дат?' : 'Why are there two date blocks?'}</strong>
              <p style={{ margin: '4px 0 8px 0', lineHeight: 1.4 }}>
                {language === 'ua' 
                  ? 'Перший блок — це загальні дати початку та закінчення заходу для афіші. Другий блок (Сесії) — це фактичні дати та сеанси для бронювання столів або купівлі квитків. Кожне бронювання привʼязується до конкретної сесії (дня).'
                  : language === 'ru'
                  ? 'Первый блок — это общие даты начала и окончания мероприятия для афиши. Второй блок (Сессии) — это фактические даты и сеансы для бронирования столов или покупки билетов. Каждое бронирование привязывается к конкретной сессии (дню).'
                  : 'The first block is the general start/end dates of the event for posters. The second block (Sessions) is the actual dates/slots for booking tables or buying tickets. Each booking is linked to a specific session.'}
              </p>
              <button
                type="button"
                className="btn btn-small btn-secondary"
                disabled={sessionsSaving}
                onClick={autoGenerateSessions}
                style={{ fontSize: 12 }}
              >
                ⚡ {language === 'ua' ? 'Автогенерація сесій на основі дат заходу' : language === 'ru' ? 'Автогенерация сессий на основе дат мероприятия' : 'Auto-generate sessions based on event dates'}
              </button>
            </div>

            {sessions.length === 0 ? (
              <p className="muted" style={{ margin: '8px 0', fontSize: 13 }}>{t('eventsAdmin.noSessions')}</p>
            ) : (
              <div style={{ margin: '8px 0' }}>
                {sessions.map((session, idx) => {
                  const key = editId ? session.id : idx;
                  const name = session.name ? localizeField(session.name, language) : '';
                  const startStr = session.startsAt ? formatDateTime(session.startsAt, language === 'ua' ? 'uk-UA' : language === 'ru' ? 'ru-RU' : 'en-US') : '';
                  const endStr = session.endsAt ? formatDateTime(session.endsAt, language === 'ua' ? 'uk-UA' : language === 'ru' ? 'ru-RU' : 'en-US') : '';
                  return (
                    <div key={key} className="admin-inline-item" style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '4px 0' }}>
                      <span style={{ fontSize: 13 }}>
                        {name ? `${name} · ` : ''}{startStr}{endStr ? ` — ${endStr}` : ''}
                        {' · '}
                        <strong>{session.admissionMode === 'FREE'
                          ? (language === 'ua' ? 'Вхід вільний' : language === 'ru' ? 'Вход свободный' : 'Free entry')
                          : (language === 'ua' ? 'За квитком' : language === 'ru' ? 'По билету' : 'Ticket required')}</strong>
                      </span>
                      <div style={{ display: 'flex', gap: 8 }}>
                        <button type="button" className="btn btn-small btn-secondary" onClick={() => handleEditSession(editId ? session.id : idx)}>{t('common.edit')}</button>
                        <button type="button" className="btn btn-small btn-danger" onClick={() => handleDeleteSession(editId ? session.id : idx)}>{t('common.delete')}</button>
                      </div>
                    </div>
                  );
                })}
              </div>
            )}

            <div style={{ display: 'flex', gap: 8, flexWrap: 'wrap', alignItems: 'end', marginTop: 8 }}>
              <label style={{ flex: '1 0 140px' }}>
                {t('eventsAdmin.form.fields.name')} (опц)
                <input value={localizeField(sessionForm.name, language)} onChange={(e) => setSessionForm({ ...sessionForm, name: { ...sessionForm.name, [language]: e.target.value } })} style={{ fontSize: 12 }} />
              </label>
              <label style={{ flex: '1 0 160px' }}>
                {t('eventsAdmin.form.fields.start')} <span className="required">*</span>
                <input type="datetime-local" value={sessionForm.startsAt} onChange={(e) => setSessionForm({ ...sessionForm, startsAt: e.target.value })} style={{ fontSize: 12 }} />
              </label>
              <label style={{ flex: '1 0 160px' }}>
                {t('eventsAdmin.form.fields.end')} <span className="required">*</span>
                <input type="datetime-local" value={sessionForm.endsAt} onChange={(e) => setSessionForm({ ...sessionForm, endsAt: e.target.value })} style={{ fontSize: 12 }} />
              </label>
              <label style={{ flex: '1 0 150px' }}>
                {language === 'ua' ? 'Умови входу' : language === 'ru' ? 'Условия входа' : 'Admission'}
                <select value={sessionForm.admissionMode} onChange={(e) => setSessionForm({ ...sessionForm, admissionMode: e.target.value })} style={{ fontSize: 12 }}>
                  <option value="TICKETED">{language === 'ua' ? 'За квитком' : language === 'ru' ? 'По билету' : 'Ticket required'}</option>
                  <option value="FREE">{language === 'ua' ? 'Вхід вільний' : language === 'ru' ? 'Вход свободный' : 'Free entry'}</option>
                </select>
              </label>
              <label className="menu-admin-checkbox" style={{ marginBottom: 2 }}>
                <input type="checkbox" checked={sessionForm.isActive} onChange={(e) => setSessionForm({ ...sessionForm, isActive: e.target.checked })} />
                <span style={{ fontSize: 12 }}>{t('eventsAdmin.form.fields.active')}</span>
              </label>
              <div style={{ display: 'flex', gap: 4, marginBottom: 2 }}>
                <button type="button" className="btn btn-small" disabled={sessionsSaving} onClick={handleSaveSession}>
                  {sessionsSaving ? t('eventsAdmin.form.saving') : (editingSessionId !== null ? t('common.save') : t('common.create'))}
                </button>
                {editingSessionId !== null ? (
                  <button type="button" className="btn btn-small btn-secondary" onClick={() => { setEditingSessionId(null); setSessionForm({ name: { ua: '', ru: '', en: '' }, startsAt: '', endsAt: '', isActive: true, admissionMode: 'TICKETED' }); }}>
                    {t('eventsAdmin.form.cancel')}
                  </button>
                ) : null}
              </div>
            </div>

            <div style={{ marginTop: '1.5rem' }}>
              <strong>{t('eventsAdmin.form.fields.shortDescription')}</strong>
              <div className="locale-tabs" style={{ margin: '6px 0' }}>
                {['ua', 'ru', 'en'].map((loc) => (
                  <button type="button" key={loc} className={`locale-tab ${activeLocale === loc ? 'active' : ''}`} onClick={() => setActiveLocale(loc)}>{loc.toUpperCase()}</button>
                ))}
              </div>
              {['ua', 'ru', 'en'].map((loc) => (
                <label key={loc} style={{ display: activeLocale === loc ? 'block' : 'none' }}>
                  {loc === 'ua' ? <span className="required">*</span> : null}
                  <textarea value={form.shortDescription[loc]} onChange={(e) => setLocalizedField('shortDescription', loc, e.target.value)} rows="3" placeholder={loc === 'ua' ? '' : t('eventsAdmin.form.placeholders.autoTranslated')} />
                </label>
              ))}
            </div>

            <div style={{ marginTop: '1.5rem' }}>
              <strong>{t('eventsAdmin.form.fields.fullDescription')}</strong>
              <div className="locale-tabs" style={{ margin: '6px 0' }}>
                {['ua', 'ru', 'en'].map((loc) => (
                  <button type="button" key={loc} className={`locale-tab ${activeLocale === loc ? 'active' : ''}`} onClick={() => setActiveLocale(loc)}>{loc.toUpperCase()}</button>
                ))}
              </div>
              {['ua', 'ru', 'en'].map((loc) => (
                <div key={loc} style={{ display: activeLocale === loc ? 'block' : 'none' }}>
                  <RichEditor
                    value={form.fullDescription[loc]}
                    onChange={(html) => setLocalizedField('fullDescription', loc, html)}
                    placeholder={loc === 'ua' ? t('eventsAdmin.form.placeholders.fullDescriptionUa') : t('eventsAdmin.form.placeholders.autoTranslated')}
                  />
                </div>
              ))}
            </div>

            <div style={{ marginTop: '1.5rem' }}>
              <strong>{t('eventsAdmin.form.fields.posterUrl')}</strong>
              <div style={{ marginTop: 8 }}>
                {form.posterImage ? (
                  <div style={{ position: 'relative', display: 'inline-block' }}>
                    <img src={form.posterImage} alt="" style={{ width: 200, height: 120, objectFit: 'cover', borderRadius: 'var(--radius-sm)' }} />
                    <button type="button" className="btn btn-small btn-danger" style={{ position: 'absolute', top: 4, right: 4, padding: '2px 8px', fontSize: 11 }} onClick={() => { setForm({ ...form, posterImage: '' }); markDirty(); }}>✕</button>
                  </div>
                ) : (
                  <label className="btn btn-secondary btn-small" style={{ cursor: 'pointer' }}>
                    {posterUploadState.status === 'uploading' ? t('common.uploading') : t('eventsAdmin.form.posterUpload')}
                    <input type="file" accept="image/png,image/jpeg,image/webp" style={{ display: 'none' }} disabled={posterUploadState.status === 'uploading'} onChange={(e) => { handlePosterUpload(e.target.files[0]); e.target.value = ''; }} />
                  </label>
                )}
                <div style={{ marginTop: 4 }}>
                  <button type="button" className="btn btn-small btn-secondary" onClick={() => setShowPosterUrl(!showPosterUrl)}>
                    {showPosterUrl ? t('eventsAdmin.form.fields.posterUrl') : t('eventsAdmin.orPasteUrl')}
                  </button>
                  {showPosterUrl ? (
                    <input value={form.posterImage} onChange={(e) => { setForm({ ...form, posterImage: e.target.value }); markDirty(); }} placeholder="https://..." style={{ marginTop: 4 }} />
                  ) : null}
                </div>
              </div>
            </div>

            <div className="grid-two-col" style={{ marginTop: '1.5rem' }}>
              <label>
                {t('eventsAdmin.form.fields.ticketUrl')}
                <input value={form.ticketUrl} onChange={(event) => { setForm({ ...form, ticketUrl: event.target.value }); markDirty(); }} placeholder="https://tickets.example.com" />
              </label>
              <label className="menu-admin-checkbox" style={{ marginTop: 28 }}>
                <input type="checkbox" checked={form.isFeatured} onChange={(event) => { setForm({ ...form, isFeatured: event.target.checked }); markDirty(); }} />
                <span>{t('eventsAdmin.form.fields.featured')}</span>
              </label>
            </div>

            {editId ? (
              <>
                <div className="admin-section-divider" style={{ marginTop: '1.5rem' }}>
                  <hr /><span>{t('eventsAdmin.sectionTicketTypes')}</span>
                </div>

                {ticketTypes.length === 0 ? (
                  <p className="muted" style={{ margin: '8px 0', fontSize: 13 }}>{t('eventsAdmin.noTicketTypes')}</p>
                ) : (
                  <div style={{ margin: '8px 0' }}>
                    {ticketTypes.map((tt) => {
                      const session = sessions.find((s) => s.id === tt.eventSessionId);
                      const sessionDate = session ? formatDateTime(session.startsAt, language === 'ua' ? 'uk-UA' : language === 'ru' ? 'ru-RU' : 'en-US') : '';
                      return (
                        <div key={tt.id} className="admin-inline-item" style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '4px 0', fontSize: 13 }}>
                          <span>
                            {localizeField(tt.name, language)} · {Number(tt.price).toFixed(2)} UAH ·                             {t('eventsAdmin.sold')} {tt.soldCount ?? 0}/{tt.capacity ?? '∞'}
                            {sessionDate ? ` · ${sessionDate}` : ''}
                          </span>
                          <div style={{ display: 'flex', gap: 8, alignItems: 'center' }}>
                            <button type="button" className="btn-link btn-small" onClick={() => toggleTicketType(tt.id, !tt.isActive)} style={{ color: tt.isActive ? 'var(--color-danger)' : 'var(--color-success)' }}>
                              {tt.isActive ? t('eventsAdmin.hide') : t('eventsAdmin.show')}
                            </button>
                            <button type="button" className="btn btn-small btn-secondary" onClick={() => handleEditTicketType(tt.id)}>{t('common.edit')}</button>
                            <button type="button" className="btn btn-small btn-danger" onClick={() => { if (window.confirm(t('eventsAdmin.errors.confirmDeleteTariff'))) deleteTicketType(tt.id); }}>{t('common.delete')}</button>
                          </div>
                        </div>
                      );
                    })}
                  </div>
                )}

                <div style={{ display: 'flex', gap: 8, flexWrap: 'wrap', alignItems: 'end', marginTop: 8 }}>
                  <label style={{ flex: '1 0 140px' }}>
                    {t('eventsAdmin.form.fields.name')} (UA) <span className="required">*</span>
                    <input value={typeForm.name.ua} onChange={(e) => setTypeForm({ ...typeForm, name: { ...typeForm.name, ua: e.target.value } })} style={{ fontSize: 12 }} />
                  </label>
                  <label style={{ flex: '1 0 140px' }}>
                    {t('eventsAdmin.form.fields.price')} <span className="required">*</span>
                    <input type="number" step="0.01" min="0" value={typeForm.price} onChange={(e) => setTypeForm({ ...typeForm, price: e.target.value })} style={{ fontSize: 12 }} />
                  </label>
                  <label style={{ flex: '0 0 100px' }}>
                    {t('eventsAdmin.form.fields.capacity')}
                    <input type="number" min="0" value={typeForm.capacity} onChange={(e) => setTypeForm({ ...typeForm, capacity: e.target.value })} style={{ fontSize: 12 }} />
                  </label>
                  <label style={{ flex: '1 0 140px' }}>
                    {t('eventsAdmin.form.fields.session')}
                    <select value={typeForm.eventSessionId} onChange={(e) => setTypeForm({ ...typeForm, eventSessionId: e.target.value })} style={{ fontSize: 12 }}>
                      <option value="">{t('common.all')}</option>
                      {sessions.map((s) => (
                        <option key={s.id} value={s.id}>
                          {formatDateTime(s.startsAt, language === 'ua' ? 'uk-UA' : language === 'ru' ? 'ru-RU' : 'en-US')}
                        </option>
                      ))}
                    </select>
                  </label>
                  <div style={{ display: 'flex', gap: 4, marginBottom: 2 }}>
                    <button type="button" className="btn btn-small" disabled={typesSaving} onClick={saveTicketType}>
                      {typesSaving ? t('eventsAdmin.form.saving') : (editingTypeId ? t('common.save') : t('common.create'))}
                    </button>
                    {editingTypeId ? (
                      <button type="button" className="btn btn-small btn-secondary" onClick={() => { setEditingTypeId(null); setTypeForm({ name: { ua: '', ru: '', en: '' }, price: '', capacity: '', eventSessionId: '' }); }}>
                        {t('eventsAdmin.form.cancel')}
                      </button>
                    ) : null}
                  </div>
                </div>
              </>
            ) : null}

            <div className="actions compact" style={{ marginTop: '1.5rem' }}>
              <button type="button" className="btn btn-secondary btn-small" onClick={autoTranslateAll} disabled={!!Object.values(translating).some(Boolean)}>
                {Object.values(translating).some(Boolean) ? t('eventsAdmin.form.translating') : t('eventsAdmin.form.translate')}
              </button>
            </div>

            <div className="actions" style={{ marginTop: '0.5rem' }}>
              <button type="submit" className="btn" disabled={!!savingKey}>
                {savingKey === 'event-form' ? t('eventsAdmin.form.saving') : (editId ? t('eventsAdmin.form.save') : t('eventsAdmin.form.create'))}
              </button>
              {editId ? <button type="button" className="btn btn-secondary" onClick={resetForm}>{t('eventsAdmin.form.cancel')}</button> : null}
              {publicPreviewHref ? (
                <a className="btn btn-secondary" href={publicPreviewHref} target="_blank" rel="noreferrer">
                  {t('eventsAdmin.form.openPublic')}
                </a>
              ) : null}
            </div>

            {feedback.message ? <p className={feedback.tone === 'error' ? 'error' : 'success'}>{feedback.message}</p> : null}
          </form>
        </PanelCard>

        <PanelCard title={t('eventsAdmin.form.preview')} subtitle="">
          <div className="menu-admin-image-preview" style={{ width: '100%', maxWidth: 360 }}>
            <img src={form.posterImage || '/icons/lebedi.jpg'} alt={localizeField(form.title, language) || t('eventsAdmin.form.preview')} />
          </div>

          <div style={{ marginTop: 16, display: 'grid', gap: 12 }}>
            <div className="menu-admin-badges">
              <span className="status-pill neutral">{t(`eventsAdmin.statusOptions.${form.status}`)}</span>
              <span className="status-pill neutral">{t(`eventsAdmin.ctaOptions.${form.ctaType}`)}</span>
              {form.isFeatured ? <span className="status-pill success">{t('eventsAdmin.form.fields.featured')}</span> : null}
            </div>
            <h3>{localizeField(form.title, language) || t('eventsAdmin.form.previewTitle')}</h3>
            {form.startAt ? (
              <p className="muted">
                {formatDateTime(fromDateTimeLocal(form.startAt), language === 'ua' ? 'uk-UA' : (language === 'ru' ? 'ru-RU' : 'en-US'))}
                {form.endAt ? ` - ${formatDateTime(fromDateTimeLocal(form.endAt), language === 'ua' ? 'uk-UA' : (language === 'ru' ? 'ru-RU' : 'en-US'))}` : ''}
              </p>
            ) : null}
            <p className="muted">{localizeField(form.shortDescription, language) || t('eventsAdmin.form.previewDescription')}</p>
            {localizeField(form.fullDescription, language) ? <p>{localizeField(form.fullDescription, language)}</p> : null}
            {form.ticketUrl ? <p><strong>{t('eventsAdmin.form.fields.ticketUrl')}:</strong> {form.ticketUrl}</p> : null}
            {publicPreviewHref ? (
              <a href={publicPreviewHref} target="_blank" rel="noreferrer" className="text-link">
                /events/{form.slug}
              </a>
            ) : (
              <p className="muted">{t('eventsAdmin.form.previewHint')}</p>
            )}
          </div>
        </PanelCard>
      </div>
    </AdminLayout>
  );
}
