ALTER TYPE "MapObjectType" ADD VALUE IF NOT EXISTS 'STAIRS';
ALTER TYPE "MapObjectType" ADD VALUE IF NOT EXISTS 'PATH';

ALTER TABLE "Map"
ADD COLUMN "backgroundColor" TEXT;

ALTER TABLE "VenueTable"
ADD COLUMN "photoUrl" TEXT;
